# Generated by Django 5.0.3 on 2024-04-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_post_friends_friendship"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendship",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
    ]
