# Generated by Django 5.0.3 on 2024-04-14 18:47

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_profile_date_of_birth_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to=account.models.user_directory_path
            ),
        ),
    ]
